// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kostinp/edu-platform-backend/internal/shared/config"
	"github.com/kostinp/edu-platform-backend/internal/shared/db"
	"github.com/kostinp/edu-platform-backend/internal/user"
	"github.com/kostinp/edu-platform-backend/internal/user/repository"
	"github.com/kostinp/edu-platform-backend/internal/user/transport/http"
	"github.com/kostinp/edu-platform-backend/internal/user/usecase"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/kostinp/edu-platform-backend/docs"
)

// Injectors from wire.go:

// Главный wire-компонент
func InitializeServer(cfg *config.Config) (*echo.Echo, error) {
	pool := db.ConnectPostgres(cfg)
	postgresUserRepository := repository.NewPostgresUserRepository(pool)
	postgresSessionRepository := repository.NewPostgresSessionRepository(pool)
	sessionUsecaseImpl := usecase.NewSessionUsecase(postgresSessionRepository)
	userService := usecase.NewUserService(postgresUserRepository, sessionUsecaseImpl)
	userHandler := transport.NewUserHandler(userService)
	postgresVisitorEventRepo := repository.NewPostgresVisitorEventRepo(pool)
	visitorEventUsecase := usecase.NewVisitorEventUsecase(postgresVisitorEventRepo)
	visitorEventHandler := transport.NewVisitorEventHandler(visitorEventUsecase)
	botToken := user.ProvideBotToken(cfg)
	jwtSecret := user.ProvideJwtSecret(cfg)
	telegramAuthHandler := transport.NewTelegramAuthHandler(userService, botToken, jwtSecret)
	sessionHandler := transport.NewSessionHandler(sessionUsecaseImpl)
	echoEcho, err := newEchoServer(cfg, userHandler, visitorEventHandler, telegramAuthHandler, sessionHandler, sessionUsecaseImpl, userService)
	if err != nil {
		return nil, err
	}
	return echoEcho, nil
}

// Для middleware и background job'ов
func InitializeSessionUsecase(cfg *config.Config) (usecase.SessionUsecase, error) {
	pool := db.ConnectPostgres(cfg)
	postgresSessionRepository := repository.NewPostgresSessionRepository(pool)
	sessionUsecaseImpl := usecase.NewSessionUsecase(postgresSessionRepository)
	return sessionUsecaseImpl, nil
}
