env: staging
server:
  host: "0.0.0.0"
  port: 8080
db:
  user: postgres
  password: yourpassword
  host: localhost
  port: 5432
  name: edu_platform
telegram:
  token: "8034975066:AAFAHoaNHmbQlaUaL-VVsoUENas26rHdlwo" #codesigned_stage_bot
  webhook_url: "https://codesigned.ru/api/telegram/webhook"
jwt:
  secret: "your-secret"
  default_expiry_days: 180
